### ISSUE TITLE
Проверка

### ISSUE THREAD

**Issue by alexGoLyceum** [Barsenick/calculator#1]
Вроде бы нормально, но при таком запросе выдает неверный результат
Пример запроса
```json
{
    "expression": "5"
}
```
Ответ сервиса
```json
{
    "result": "0"
}
```

**Comment by fhcirf111** [comment]
Вообще, изначально я хотел сделать это ошибкой, ибо здесь нечего считать. Хорошо, доработаю, спасибо.

**Comment by Barsenick** [comment]
**Готово**
